### ISSUE TITLE
How to evaluate the depth image for real-world images?

### ISSUE THREAD

**Issue by angleboy8** [shawLyu/HR-Depth#15]
Hi. Thank you for your excellent work very much. Please how to estimate the depth map for real-world images. Similar to [Monodepth2](https://github.com/nianticlabs/monodepth2), I didn't find the instructions about it. If you have any information, please let me know it. I am very grateful for your help.

**Comment by dan0910** [comment]
> Hi. Thank you for your excellent work very much. Please how to estimate the depth map for real-world images. Similar to [Monodepth2](https://github.com/nianticlabs/monodepth2), I didn't find the instructions about it. If you have any information, please let me know it. I am very grateful for your help.

Hi～I have the same question. 
And I find that using different models to infer the same image, the numerical range of the output varies greatly

**Comment by shawLyu** [comment]
Thanks for paying attention to this work, and I'm sorry for the late reply.  The problem you mentioned is called scale ambiguity in all monocular depth estimation methods whether supervised or unsupervised. In unsupervised depth estimation tasks, we always use a median scale to align the scale between predicted depth and ground truth depth. For real-world images, obtaining the absolute scale of depth is hard and we can only get relative results. If you have more questions, you can leave your message under this issue. Because the journal paper is still under review, we are waiting for the decision and will open source more results later.
