### ISSUE TITLE
Experimental results without pretrained

### ISSUE THREAD

**Issue by YagumaLi** [shawLyu/HR-Depth#9]
Hi,
 
Thanks for your amazing work! It gives me a lot of inspiration.
And have you ever tried training your network without pretrained, and test the trained network at different resolutions?
If so, could you please give me some cues to find them?

I will appreciate it if you reply to me. Thanks a lot.

**Comment by shawLyu** [comment]
Thanks for your attention.

1. Yes, I had tried to train our network from scratch. The performance of this setting is bad, you can see it below.
model_name & abs rel & sq rel & RMSE & log_RMSE & /delta < 1.25 & /delta < 1.25 ^2 & /delta < 1.25 ^3
HR-Depth (640 x 192) | 0.130 | 1.004 | 5.077 | 0.207 | 0.847 | 0.950 | 0.978

2. The resolution of training set and testing set should be consistent. I think this is due to the kernel size of the convolution.

Hope this answer can help you!

**Comment by YagumaLi** [comment]
Thanks for your reply.
This is what I need. Thanks so much.

And can I use this results as comparison in my paper if it is necessary in the future?
Should I just cite your paper or this website?

Thanks a lot!

**Comment by shawLyu** [comment]
Yes, you can use this result in your paper and I think citing the paper is enough. 

If you have any other questions, you can email to me. Thanks!

**Comment by YagumaLi** [comment]
Thanks a lot!
